# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Author")

model.instance <- Author$new()

test_that("Authors", {
  # tests for the property `Authors` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`Authors`, "EXPECTED_RESULT")
})

test_that("BookAuthors", {
  # tests for the property `BookAuthors` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`BookAuthors`, "EXPECTED_RESULT")
})

test_that("BookGroupAuthors", {
  # tests for the property `BookGroupAuthors` (array[character])
  # Book authors if In case of a book series

  # uncomment below to test the property 
  #expect_equal(model.instance$`BookGroupAuthors`, "EXPECTED_RESULT")
})

