# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WosLiteResponse")

model.instance <- WosLiteResponse$new()

test_that("QueryResult", {
  # tests for the property `QueryResult` (QueryResult)

  # uncomment below to test the property 
  #expect_equal(model.instance$`QueryResult`, "EXPECTED_RESULT")
})

test_that("Data", {
  # tests for the property `Data` (array[WosLiteRecord])
  # The array of the Web of Science records

  # uncomment below to test the property 
  #expect_equal(model.instance$`Data`, "EXPECTED_RESULT")
})

