# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test ErrorResponse")

model.instance <- ErrorResponse$new()

test_that("code", {
  # tests for the property `code` (character)
  # The error code (mostly the HTTP status description)

  # uncomment below to test the property 
  #expect_equal(model.instance$`code`, "EXPECTED_RESULT")
})

test_that("message", {
  # tests for the property `message` (character)
  # A detailed message of the error that helps you to correct your request.

  # uncomment below to test the property 
  #expect_equal(model.instance$`message`, "EXPECTED_RESULT")
})

test_that("id", {
  # tests for the property `id` (character)
  # The request ID which can be used for investigation purposes.

  # uncomment below to test the property 
  #expect_equal(model.instance$`id`, "EXPECTED_RESULT")
})

