# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Keyword")

model.instance <- Keyword$new()

test_that("Keywords", {
  # tests for the property `Keywords` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`Keywords`, "EXPECTED_RESULT")
})

