# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WosLiteRecord")

model.instance <- WosLiteRecord$new()

test_that("UT", {
  # tests for the property `UT` (character)
  # The unique identifier of Web of Science Record

  # uncomment below to test the property 
  #expect_equal(model.instance$`UT`, "EXPECTED_RESULT")
})

test_that("Title", {
  # tests for the property `Title` (WosLiteRecordTitle)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Title`, "EXPECTED_RESULT")
})

test_that("Doctype", {
  # tests for the property `Doctype` (Doctype)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Doctype`, "EXPECTED_RESULT")
})

test_that("Source", {
  # tests for the property `Source` (Source)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Source`, "EXPECTED_RESULT")
})

test_that("Author", {
  # tests for the property `Author` (Author)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Author`, "EXPECTED_RESULT")
})

test_that("Keyword", {
  # tests for the property `Keyword` (Keyword)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Keyword`, "EXPECTED_RESULT")
})

test_that("Other", {
  # tests for the property `Other` (Other)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Other`, "EXPECTED_RESULT")
})

