# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test SearchApi")

api.instance <- SearchApi$new()

test_that("QueryQueryIdGet", {
  # tests for QueryQueryIdGet
  # base path: https://api.clarivate.com/api/woslite
  # Fetch record(s) by query identifier
  # This operation returns record(s) identified by a query identifier.
  # @param query.id integer Retrieve records based on query identifier.
  # @param count integer Number of records to return, must be 0-100.
  # @param first.record integer Specific record, if any within the result set to return. Cannot be less than 1 and greater than 100000.
  # @param sort.field character Order by field(s). Field name and order by clause separated by '+', use A for ASC and D for DESC, ex: PY+D. Multiple values are separated by comma. If sortField was set on the original query, this parameter should be set as sorting is not a property of the query. (optional)
  # @return [WosLiteResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

test_that("RootGet", {
  # tests for RootGet
  # base path: https://api.clarivate.com/api/woslite
  # Submits a user query and returns results
  # The search operation submits a search query to the specified database edition and retrieves data. This operation returns a query ID that can be used in subsequent operations to retrieve more records.
  # @param database.id character Database to search. Must be a valid database ID, one of the following: BCI/BIOABS/BIOSIS/CCC/DCI/DIIDW/MEDLINE/WOK/WOS/ZOOREC. WOK represents all databases.
  # @param usr.query character User query for requesting data, ex: TS=(cadmium). The query parser will return errors for invalid queries.
  # @param count integer Number of records to return, must be 0-100.
  # @param first.record integer Specific record, if any within the result set to return. Cannot be less than 1 and greater than 100000.
  # @param lang character Language of search. This element can take only one value: en for English. If no language is specified, English is passed by default. (optional)
  # @param edition character Edition(s) to be searched. If null, user permissions will be substituted. Must include the name of the collection and edition name separated by '+', ex: WOS+SCI. Multiple editions are separated by ','. Editions available for collection(WOS) - AHCI,CCR,IC,ISSHP,ISTP,SCI,SSCI,BHCI,BSCI and ESCI. (optional)
  # @param publish.time.span character This element specifies a range of publication dates. If publishTimeSpan is used, the loadTimeSpan parameter must be omitted. If publishTimeSpan and loadTimeSpan are both omitted, then the maximum time span will be inferred from the editions data. Beginning and end dates should be specified in the yyyy-mm-dd format separated by +, ex: 1993-01-01+2009-12-31. (optional)
  # @param load.time.span character Load time span (otherwise described as symbolic time span) defines a range of load dates. The load date is the date a record was added to the database. If load date is specified, the publishTimeSpan parameter must be omitted. If both publishTimeSpan and loadTimeSpan are omitted, the maximum publication date will be inferred from the editions data. Any of D/W/M/Y prefixed with a number where D-Day, M-Month, W-Week, Y-Year allowed. Acceptable value range for Day(0-6), Week(1-52), Month(1-12) and Year(0-10), ex: 5D,30W,10M,8Y. (optional)
  # @param sort.field character Order by field(s). Field name and order by clause separated by '+', use A for ASC and D for DESC, ex: PY+D. Multiple values are separated by comma. (optional)
  # @return [WosLiteResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

