# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test WosLiteRecordTitle")

model.instance <- WosLiteRecordTitle$new()

test_that("Title", {
  # tests for the property `Title` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`Title`, "EXPECTED_RESULT")
})

