# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test IntegrationApi")

api.instance <- IntegrationApi$new()

test_that("IdUniqueIdGet", {
  # tests for IdUniqueIdGet
  # base path: https://api.clarivate.com/api/woslite
  # Find record(s) by specific id
  # This operation returns a record identified by a unique identifier. You may specify multiple identifiers in a single request.
  # @param database.id character Database to search. Must be a valid database ID, one of the following: BCI/BIOABS/BIOSIS/CCC/DCI/DIIDW/MEDLINE/WOK/WOS/ZOOREC. WOK represents all databases.
  # @param unique.id character Primary item(s) id to be searched, ex: WOS:000270372400005. Cannot be null or an empty string. Multiple values are separated by comma.
  # @param count integer Number of records returned in the request
  # @param first.record integer Specific record, if any within the result set to return. Cannot be less than 1 and greater than 100000.
  # @param lang character Language of search. This element can take only one value: en for English. If no language is specified, English is passed by default. (optional)
  # @param sort.field character Order by field(s). Field name and order by clause separated by '+', use A for ASC and D for DESC, ex: PY+D. Multiple values are separated by comma. (optional)
  # @return [WosLiteResponse]

  # uncomment below to test the operation
  #expect_equal(result, "EXPECTED_RESULT")
})

