# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Source")

model.instance <- Source$new()

test_that("Pages", {
  # tests for the property `Pages` (array[character])
  # Pages range in the source

  # uncomment below to test the property 
  #expect_equal(model.instance$`Pages`, "EXPECTED_RESULT")
})

test_that("SourceTitle", {
  # tests for the property `SourceTitle` (array[character])
  # The title of the source in which the document was published

  # uncomment below to test the property 
  #expect_equal(model.instance$`SourceTitle`, "EXPECTED_RESULT")
})

test_that("Issue", {
  # tests for the property `Issue` (array[character])
  # Issue Number

  # uncomment below to test the property 
  #expect_equal(model.instance$`Issue`, "EXPECTED_RESULT")
})

test_that("Volume", {
  # tests for the property `Volume` (array[character])
  # Volume number

  # uncomment below to test the property 
  #expect_equal(model.instance$`Volume`, "EXPECTED_RESULT")
})

test_that("SpecialIssue", {
  # tests for the property `SpecialIssue` (array[character])
  # Special issue, in case was published to a special issue journal

  # uncomment below to test the property 
  #expect_equal(model.instance$`SpecialIssue`, "EXPECTED_RESULT")
})

test_that("BookSeriesTitle", {
  # tests for the property `BookSeriesTitle` (array[character])
  # Book series title - in case the article is published in book series

  # uncomment below to test the property 
  #expect_equal(model.instance$`BookSeriesTitle`, "EXPECTED_RESULT")
})

test_that("Published.BiblioDate", {
  # tests for the property `Published.BiblioDate` (array[character])
  # Published Date

  # uncomment below to test the property 
  #expect_equal(model.instance$`Published.BiblioDate`, "EXPECTED_RESULT")
})

test_that("Published.BiblioYear", {
  # tests for the property `Published.BiblioYear` (array[character])
  # Published Year

  # uncomment below to test the property 
  #expect_equal(model.instance$`Published.BiblioYear`, "EXPECTED_RESULT")
})

