# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Doctype")

model.instance <- Doctype$new()

test_that("Doctype", {
  # tests for the property `Doctype` (array[character])

  # uncomment below to test the property 
  #expect_equal(model.instance$`Doctype`, "EXPECTED_RESULT")
})

