# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate

context("Test Other")

model.instance <- Other$new()

test_that("Identifier.Eissn", {
  # tests for the property `Identifier.Eissn` (array[character])
  # Electronic International Standard Identifier Number. [What is an ISSN?](https://www.issn.org/understanding-the-issn/what-is-an-issn/)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Identifier.Eissn`, "EXPECTED_RESULT")
})

test_that("Contributor.ResearcherID.ResearcherIDs", {
  # tests for the property `Contributor.ResearcherID.ResearcherIDs` (array[character])
  # ResearcherID provided from Web of Science. [What is my Web of Science ResearcherID?](https://publons.freshdesk.com/support/solutions/articles/12000038281-what-is-my-web-of-science-researcherid-)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Contributor.ResearcherID.ResearcherIDs`, "EXPECTED_RESULT")
})

test_that("Contributor.ResearcherID.Names", {
  # tests for the property `Contributor.ResearcherID.Names` (array[character])
  # The author names in the same order from &#x60;Contributor.ResearcherID.ResearcherIDs&#x60;

  # uncomment below to test the property 
  #expect_equal(model.instance$`Contributor.ResearcherID.Names`, "EXPECTED_RESULT")
})

test_that("Identifier.Doi", {
  # tests for the property `Identifier.Doi` (array[character])
  # Digital Object Identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`Identifier.Doi`, "EXPECTED_RESULT")
})

test_that("Identifier.Issn", {
  # tests for the property `Identifier.Issn` (array[character])
  # International Standard Identifier Number. [What is an ISSN?](https://www.issn.org/understanding-the-issn/what-is-an-issn/)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Identifier.Issn`, "EXPECTED_RESULT")
})

test_that("Identifier.article_no", {
  # tests for the property `Identifier.article_no` (array[character])
  # Article Number

  # uncomment below to test the property 
  #expect_equal(model.instance$`Identifier.article_no`, "EXPECTED_RESULT")
})

test_that("Identifier.Isbn", {
  # tests for the property `Identifier.Isbn` (array[character])
  # International Standard Book Number. [What is an ISBN?](https://www.isbn-international.org/content/what-isbn)

  # uncomment below to test the property 
  #expect_equal(model.instance$`Identifier.Isbn`, "EXPECTED_RESULT")
})

test_that("ResearcherID.Disclaimer", {
  # tests for the property `ResearcherID.Disclaimer` (array[character])
  # Dislaimer for ResearcherID

  # uncomment below to test the property 
  #expect_equal(model.instance$`ResearcherID.Disclaimer`, "EXPECTED_RESULT")
})

test_that("Identifier.Xref_Doi", {
  # tests for the property `Identifier.Xref_Doi` (array[character])
  # Digital Object Identifier

  # uncomment below to test the property 
  #expect_equal(model.instance$`Identifier.Xref_Doi`, "EXPECTED_RESULT")
})

test_that("Identifier.Ids", {
  # tests for the property `Identifier.Ids` (array[character])
  # The IDS Number is included in the export from Web of Science to Researcher Solutions products. The ISI Document Delivery Number is used to uniquely identify documents that can be delivered via IDS. It is of no particular use if the user does not wish to use our document delivery.

  # uncomment below to test the property 
  #expect_equal(model.instance$`Identifier.Ids`, "EXPECTED_RESULT")
})

