# Web of Science API Lite
#
# A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Author
#'
#' @description Author Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field Authors  list( character ) [optional]
#'
#' @field BookAuthors  list( character ) [optional]
#'
#' @field BookGroupAuthors  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Author <- R6::R6Class(
  'Author',
  public = list(
    `Authors` = NULL,
    `BookAuthors` = NULL,
    `BookGroupAuthors` = NULL,
    initialize = function(
        `Authors`=NULL, `BookAuthors`=NULL, `BookGroupAuthors`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`Authors`)) {
        stopifnot(is.vector(`Authors`), length(`Authors`) != 0)
        sapply(`Authors`, function(x) stopifnot(is.character(x)))
        self$`Authors` <- `Authors`
      }
      if (!is.null(`BookAuthors`)) {
        stopifnot(is.vector(`BookAuthors`), length(`BookAuthors`) != 0)
        sapply(`BookAuthors`, function(x) stopifnot(is.character(x)))
        self$`BookAuthors` <- `BookAuthors`
      }
      if (!is.null(`BookGroupAuthors`)) {
        stopifnot(is.vector(`BookGroupAuthors`), length(`BookGroupAuthors`) != 0)
        sapply(`BookGroupAuthors`, function(x) stopifnot(is.character(x)))
        self$`BookGroupAuthors` <- `BookGroupAuthors`
      }
    },
    toJSON = function() {
      AuthorObject <- list()
      if (!is.null(self$`Authors`)) {
        AuthorObject[['Authors']] <-
          self$`Authors`
      }
      if (!is.null(self$`BookAuthors`)) {
        AuthorObject[['BookAuthors']] <-
          self$`BookAuthors`
      }
      if (!is.null(self$`BookGroupAuthors`)) {
        AuthorObject[['BookGroupAuthors']] <-
          self$`BookGroupAuthors`
      }

      AuthorObject
    },
    fromJSON = function(AuthorJson) {
      AuthorObject <- jsonlite::fromJSON(AuthorJson)
      if (!is.null(AuthorObject$`Authors`)) {
        self$`Authors` <- ApiClient$new()$deserializeObj(AuthorObject$`Authors`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(AuthorObject$`BookAuthors`)) {
        self$`BookAuthors` <- ApiClient$new()$deserializeObj(AuthorObject$`BookAuthors`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(AuthorObject$`BookGroupAuthors`)) {
        self$`BookGroupAuthors` <- ApiClient$new()$deserializeObj(AuthorObject$`BookGroupAuthors`, "array[character]", loadNamespace("woslite_r_client"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`Authors`)) {
        sprintf(
        '"Authors":
           [%s]
        ',
        paste(unlist(lapply(self$`Authors`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`BookAuthors`)) {
        sprintf(
        '"BookAuthors":
           [%s]
        ',
        paste(unlist(lapply(self$`BookAuthors`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`BookGroupAuthors`)) {
        sprintf(
        '"BookGroupAuthors":
           [%s]
        ',
        paste(unlist(lapply(self$`BookGroupAuthors`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AuthorJson) {
      AuthorObject <- jsonlite::fromJSON(AuthorJson)
      self$`Authors` <- ApiClient$new()$deserializeObj(AuthorObject$`Authors`, "array[character]", loadNamespace("woslite_r_client"))
      self$`BookAuthors` <- ApiClient$new()$deserializeObj(AuthorObject$`BookAuthors`, "array[character]", loadNamespace("woslite_r_client"))
      self$`BookGroupAuthors` <- ApiClient$new()$deserializeObj(AuthorObject$`BookGroupAuthors`, "array[character]", loadNamespace("woslite_r_client"))
      self
    }
  )
)

