# Web of Science API Lite
#
# A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Doctype
#'
#' @description Doctype Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field Doctype  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Doctype <- R6::R6Class(
  'Doctype',
  public = list(
    `Doctype` = NULL,
    initialize = function(
        `Doctype`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`Doctype`)) {
        stopifnot(is.vector(`Doctype`), length(`Doctype`) != 0)
        sapply(`Doctype`, function(x) stopifnot(is.character(x)))
        self$`Doctype` <- `Doctype`
      }
    },
    toJSON = function() {
      DoctypeObject <- list()
      if (!is.null(self$`Doctype`)) {
        DoctypeObject[['Doctype']] <-
          self$`Doctype`
      }

      DoctypeObject
    },
    fromJSON = function(DoctypeJson) {
      DoctypeObject <- jsonlite::fromJSON(DoctypeJson)
      if (!is.null(DoctypeObject$`Doctype`)) {
        self$`Doctype` <- ApiClient$new()$deserializeObj(DoctypeObject$`Doctype`, "array[character]", loadNamespace("woslite_r_client"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`Doctype`)) {
        sprintf(
        '"Doctype":
           [%s]
        ',
        paste(unlist(lapply(self$`Doctype`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(DoctypeJson) {
      DoctypeObject <- jsonlite::fromJSON(DoctypeJson)
      self$`Doctype` <- ApiClient$new()$deserializeObj(DoctypeObject$`Doctype`, "array[character]", loadNamespace("woslite_r_client"))
      self
    }
  )
)

