# Web of Science API Lite
#
# A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ErrorResponse
#'
#' @description ErrorResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field code  character [optional]
#'
#' @field message  character [optional]
#'
#' @field id  character [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ErrorResponse <- R6::R6Class(
  'ErrorResponse',
  public = list(
    `code` = NULL,
    `message` = NULL,
    `id` = NULL,
    initialize = function(
        `code`=NULL, `message`=NULL, `id`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`code`)) {
        stopifnot(is.character(`code`), length(`code`) == 1)
        self$`code` <- `code`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!is.null(`id`)) {
        stopifnot(is.character(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
    },
    toJSON = function() {
      ErrorResponseObject <- list()
      if (!is.null(self$`code`)) {
        ErrorResponseObject[['code']] <-
          self$`code`
      }
      if (!is.null(self$`message`)) {
        ErrorResponseObject[['message']] <-
          self$`message`
      }
      if (!is.null(self$`id`)) {
        ErrorResponseObject[['id']] <-
          self$`id`
      }

      ErrorResponseObject
    },
    fromJSON = function(ErrorResponseJson) {
      ErrorResponseObject <- jsonlite::fromJSON(ErrorResponseJson)
      if (!is.null(ErrorResponseObject$`code`)) {
        self$`code` <- ErrorResponseObject$`code`
      }
      if (!is.null(ErrorResponseObject$`message`)) {
        self$`message` <- ErrorResponseObject$`message`
      }
      if (!is.null(ErrorResponseObject$`id`)) {
        self$`id` <- ErrorResponseObject$`id`
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`code`)) {
        sprintf(
        '"code":
          "%s"
                ',
        self$`code`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          "%s"
                ',
        self$`id`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ErrorResponseJson) {
      ErrorResponseObject <- jsonlite::fromJSON(ErrorResponseJson)
      self$`code` <- ErrorResponseObject$`code`
      self$`message` <- ErrorResponseObject$`message`
      self$`id` <- ErrorResponseObject$`id`
      self
    }
  )
)

