# Web of Science API Lite
#
# A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Integration operations
#' @description woslite_r_client.Integration
#' @format An \code{R6Class} generator object
#' @field apiClient Handles the client-server communication.
#'
#' @section Methods:
#' \describe{
#' \strong{ IdUniqueIdGet } \emph{ Find record(s) by specific id }
#' This operation returns a record identified by a unique identifier. You may specify multiple identifiers in a single request.
#'
#' \itemize{
#' \item \emph{ @param } database.id character
#' \item \emph{ @param } unique.id character
#' \item \emph{ @param } count integer
#' \item \emph{ @param } first.record integer
#' \item \emph{ @param } lang character
#' \item \emph{ @param } sort.field character
#' \item \emph{ @returnType } \link{WosLiteResponse} \cr
#'
#'
#' \item status code : 200 | Success
#'
#' \item return type : WosLiteResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-RateLimit-Remaining-second \tab The number of requests left for the second window. \cr
#' X-RateLimit-Limit-second \tab The number of requests limit per second. \cr
#' x-paginate-by-query-id \tab The url of the next page in case your &#x60;RecordsFound &gt; count + firstRecord&#x60; Please use this url for pagination. The QueryId will live for four hours in case if inactivity.  \cr
#' }
#' \item status code : 0 | Error response 400+
#'
#' \item return type : ErrorResponse 
#' \item response headers :
#'
#' \tabular{ll}{
#' X-RateLimit-Remaining-second \tab The number of requests left for the second window. \cr
#' X-RateLimit-Limit-second \tab The number of requests limit per second. \cr
#' }
#' }
#'
#' }
#'
#'
#' @examples
#' \dontrun{
#' ####################  IdUniqueIdGet  ####################
#'
#' library(woslite_r_client)
#' var.database.id <- 'database.id_example' # character | Database to search. Must be a valid database ID, one of the following: BCI/BIOABS/BIOSIS/CCC/DCI/DIIDW/MEDLINE/WOK/WOS/ZOOREC. WOK represents all databases.
#' var.unique.id <- 'unique.id_example' # character | Primary item(s) id to be searched, ex: WOS:000270372400005. Cannot be null or an empty string. Multiple values are separated by comma.
#' var.count <- 10 # integer | Number of records returned in the request
#' var.first.record <- 56 # integer | Specific record, if any within the result set to return. Cannot be less than 1 and greater than 100000.
#' var.lang <- 'lang_example' # character | Language of search. This element can take only one value: en for English. If no language is specified, English is passed by default.
#' var.sort.field <- 'sort.field_example' # character | Order by field(s). Field name and order by clause separated by '+', use A for ASC and D for DESC, ex: PY+D. Multiple values are separated by comma.
#'
#' #Find record(s) by specific id
#' api.instance <- IntegrationApi$new()
#'
#' #Configure API key authorization: key
#' api.instance$apiClient$apiKeys['X-ApiKey'] <- 'TODO_YOUR_API_KEY';
#'
#' result <- api.instance$IdUniqueIdGet(var.database.id, var.unique.id, var.count, var.first.record, lang=var.lang, sort.field=var.sort.field)
#'
#'
#' }
#' @importFrom R6 R6Class
#' @importFrom base64enc base64encode
#' @export
IntegrationApi <- R6::R6Class(
  'IntegrationApi',
  public = list(
    apiClient = NULL,
    initialize = function(apiClient){
      if (!missing(apiClient)) {
        self$apiClient <- apiClient
      }
      else {
        self$apiClient <- ApiClient$new()
      }
    },
    IdUniqueIdGet = function(database.id, unique.id, count, first.record, lang=NULL, sort.field=NULL, ...){
      apiResponse <- self$IdUniqueIdGetWithHttpInfo(database.id, unique.id, count, first.record, lang, sort.field, ...)
      resp <- apiResponse$response
      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        apiResponse$content
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        apiResponse
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        apiResponse
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        apiResponse
      }
    },

    IdUniqueIdGetWithHttpInfo = function(database.id, unique.id, count, first.record, lang=NULL, sort.field=NULL, ...){
      args <- list(...)
      queryParams <- list()
      headerParams <- c()

      if (missing(`database.id`)) {
        stop("Missing required parameter `database.id`.")
      }

      if (missing(`unique.id`)) {
        stop("Missing required parameter `unique.id`.")
      }

      if (missing(`count`)) {
        stop("Missing required parameter `count`.")
      }

      if (missing(`first.record`)) {
        stop("Missing required parameter `first.record`.")
      }

      queryParams['databaseId'] <- database.id

      queryParams['lang'] <- lang

      queryParams['count'] <- count

      queryParams['firstRecord'] <- first.record

      queryParams['sortField'] <- sort.field

      body <- NULL
      urlPath <- "/id/{uniqueId}"
      if (!missing(`unique.id`)) {
        urlPath <- gsub(paste0("\\{", "uniqueId", "\\}"), URLencode(as.character(`unique.id`), reserved = TRUE), urlPath)
      }

      # API key authentication
      if ("X-ApiKey" %in% names(self$apiClient$apiKeys) && nchar(self$apiClient$apiKeys["X-ApiKey"]) > 0) {
        headerParams['X-ApiKey'] <- paste(unlist(self$apiClient$apiKeys["X-ApiKey"]), collapse='')
      }

      resp <- self$apiClient$CallApi(url = paste0(self$apiClient$basePath, urlPath),
                                 method = "GET",
                                 queryParams = queryParams,
                                 headerParams = headerParams,
                                 body = body,
                                 ...)

      if (httr::status_code(resp) >= 200 && httr::status_code(resp) <= 299) {
        deserializedRespObj <- tryCatch(
          self$apiClient$deserialize(resp, "WosLiteResponse", loadNamespace("woslite_r_client")),
          error = function(e){
             stop("Failed to deserialize response")
          }
        )
        ApiResponse$new(deserializedRespObj, resp)
      } else if (httr::status_code(resp) >= 300 && httr::status_code(resp) <= 399) {
        ApiResponse$new(paste("Server returned " , httr::status_code(resp) , " response status code."), resp)
      } else if (httr::status_code(resp) >= 400 && httr::status_code(resp) <= 499) {
        ApiResponse$new("API client error", resp)
      } else if (httr::status_code(resp) >= 500 && httr::status_code(resp) <= 599) {
        ApiResponse$new("API server error", resp)
      }
    }
  )
)
