# Web of Science API Lite
#
# A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Keyword
#'
#' @description Keyword Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field Keywords  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Keyword <- R6::R6Class(
  'Keyword',
  public = list(
    `Keywords` = NULL,
    initialize = function(
        `Keywords`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`Keywords`)) {
        stopifnot(is.vector(`Keywords`), length(`Keywords`) != 0)
        sapply(`Keywords`, function(x) stopifnot(is.character(x)))
        self$`Keywords` <- `Keywords`
      }
    },
    toJSON = function() {
      KeywordObject <- list()
      if (!is.null(self$`Keywords`)) {
        KeywordObject[['Keywords']] <-
          self$`Keywords`
      }

      KeywordObject
    },
    fromJSON = function(KeywordJson) {
      KeywordObject <- jsonlite::fromJSON(KeywordJson)
      if (!is.null(KeywordObject$`Keywords`)) {
        self$`Keywords` <- ApiClient$new()$deserializeObj(KeywordObject$`Keywords`, "array[character]", loadNamespace("woslite_r_client"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`Keywords`)) {
        sprintf(
        '"Keywords":
           [%s]
        ',
        paste(unlist(lapply(self$`Keywords`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(KeywordJson) {
      KeywordObject <- jsonlite::fromJSON(KeywordJson)
      self$`Keywords` <- ApiClient$new()$deserializeObj(KeywordObject$`Keywords`, "array[character]", loadNamespace("woslite_r_client"))
      self
    }
  )
)

