# Web of Science API Lite
#
# A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Other
#'
#' @description Other Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field Identifier.Eissn  list( character ) [optional]
#'
#' @field Contributor.ResearcherID.ResearcherIDs  list( character ) [optional]
#'
#' @field Contributor.ResearcherID.Names  list( character ) [optional]
#'
#' @field Identifier.Doi  list( character ) [optional]
#'
#' @field Identifier.Issn  list( character ) [optional]
#'
#' @field Identifier.article_no  list( character ) [optional]
#'
#' @field Identifier.Isbn  list( character ) [optional]
#'
#' @field ResearcherID.Disclaimer  list( character ) [optional]
#'
#' @field Identifier.Xref_Doi  list( character ) [optional]
#'
#' @field Identifier.Ids  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Other <- R6::R6Class(
  'Other',
  public = list(
    `Identifier.Eissn` = NULL,
    `Contributor.ResearcherID.ResearcherIDs` = NULL,
    `Contributor.ResearcherID.Names` = NULL,
    `Identifier.Doi` = NULL,
    `Identifier.Issn` = NULL,
    `Identifier.article_no` = NULL,
    `Identifier.Isbn` = NULL,
    `ResearcherID.Disclaimer` = NULL,
    `Identifier.Xref_Doi` = NULL,
    `Identifier.Ids` = NULL,
    initialize = function(
        `Identifier.Eissn`=NULL, `Contributor.ResearcherID.ResearcherIDs`=NULL, `Contributor.ResearcherID.Names`=NULL, `Identifier.Doi`=NULL, `Identifier.Issn`=NULL, `Identifier.article_no`=NULL, `Identifier.Isbn`=NULL, `ResearcherID.Disclaimer`=NULL, `Identifier.Xref_Doi`=NULL, `Identifier.Ids`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`Identifier.Eissn`)) {
        stopifnot(is.vector(`Identifier.Eissn`), length(`Identifier.Eissn`) != 0)
        sapply(`Identifier.Eissn`, function(x) stopifnot(is.character(x)))
        self$`Identifier.Eissn` <- `Identifier.Eissn`
      }
      if (!is.null(`Contributor.ResearcherID.ResearcherIDs`)) {
        stopifnot(is.vector(`Contributor.ResearcherID.ResearcherIDs`), length(`Contributor.ResearcherID.ResearcherIDs`) != 0)
        sapply(`Contributor.ResearcherID.ResearcherIDs`, function(x) stopifnot(is.character(x)))
        self$`Contributor.ResearcherID.ResearcherIDs` <- `Contributor.ResearcherID.ResearcherIDs`
      }
      if (!is.null(`Contributor.ResearcherID.Names`)) {
        stopifnot(is.vector(`Contributor.ResearcherID.Names`), length(`Contributor.ResearcherID.Names`) != 0)
        sapply(`Contributor.ResearcherID.Names`, function(x) stopifnot(is.character(x)))
        self$`Contributor.ResearcherID.Names` <- `Contributor.ResearcherID.Names`
      }
      if (!is.null(`Identifier.Doi`)) {
        stopifnot(is.vector(`Identifier.Doi`), length(`Identifier.Doi`) != 0)
        sapply(`Identifier.Doi`, function(x) stopifnot(is.character(x)))
        self$`Identifier.Doi` <- `Identifier.Doi`
      }
      if (!is.null(`Identifier.Issn`)) {
        stopifnot(is.vector(`Identifier.Issn`), length(`Identifier.Issn`) != 0)
        sapply(`Identifier.Issn`, function(x) stopifnot(is.character(x)))
        self$`Identifier.Issn` <- `Identifier.Issn`
      }
      if (!is.null(`Identifier.article_no`)) {
        stopifnot(is.vector(`Identifier.article_no`), length(`Identifier.article_no`) != 0)
        sapply(`Identifier.article_no`, function(x) stopifnot(is.character(x)))
        self$`Identifier.article_no` <- `Identifier.article_no`
      }
      if (!is.null(`Identifier.Isbn`)) {
        stopifnot(is.vector(`Identifier.Isbn`), length(`Identifier.Isbn`) != 0)
        sapply(`Identifier.Isbn`, function(x) stopifnot(is.character(x)))
        self$`Identifier.Isbn` <- `Identifier.Isbn`
      }
      if (!is.null(`ResearcherID.Disclaimer`)) {
        stopifnot(is.vector(`ResearcherID.Disclaimer`), length(`ResearcherID.Disclaimer`) != 0)
        sapply(`ResearcherID.Disclaimer`, function(x) stopifnot(is.character(x)))
        self$`ResearcherID.Disclaimer` <- `ResearcherID.Disclaimer`
      }
      if (!is.null(`Identifier.Xref_Doi`)) {
        stopifnot(is.vector(`Identifier.Xref_Doi`), length(`Identifier.Xref_Doi`) != 0)
        sapply(`Identifier.Xref_Doi`, function(x) stopifnot(is.character(x)))
        self$`Identifier.Xref_Doi` <- `Identifier.Xref_Doi`
      }
      if (!is.null(`Identifier.Ids`)) {
        stopifnot(is.vector(`Identifier.Ids`), length(`Identifier.Ids`) != 0)
        sapply(`Identifier.Ids`, function(x) stopifnot(is.character(x)))
        self$`Identifier.Ids` <- `Identifier.Ids`
      }
    },
    toJSON = function() {
      OtherObject <- list()
      if (!is.null(self$`Identifier.Eissn`)) {
        OtherObject[['Identifier.Eissn']] <-
          self$`Identifier.Eissn`
      }
      if (!is.null(self$`Contributor.ResearcherID.ResearcherIDs`)) {
        OtherObject[['Contributor.ResearcherID.ResearcherIDs']] <-
          self$`Contributor.ResearcherID.ResearcherIDs`
      }
      if (!is.null(self$`Contributor.ResearcherID.Names`)) {
        OtherObject[['Contributor.ResearcherID.Names']] <-
          self$`Contributor.ResearcherID.Names`
      }
      if (!is.null(self$`Identifier.Doi`)) {
        OtherObject[['Identifier.Doi']] <-
          self$`Identifier.Doi`
      }
      if (!is.null(self$`Identifier.Issn`)) {
        OtherObject[['Identifier.Issn']] <-
          self$`Identifier.Issn`
      }
      if (!is.null(self$`Identifier.article_no`)) {
        OtherObject[['Identifier.article_no']] <-
          self$`Identifier.article_no`
      }
      if (!is.null(self$`Identifier.Isbn`)) {
        OtherObject[['Identifier.Isbn']] <-
          self$`Identifier.Isbn`
      }
      if (!is.null(self$`ResearcherID.Disclaimer`)) {
        OtherObject[['ResearcherID.Disclaimer']] <-
          self$`ResearcherID.Disclaimer`
      }
      if (!is.null(self$`Identifier.Xref_Doi`)) {
        OtherObject[['Identifier.Xref_Doi']] <-
          self$`Identifier.Xref_Doi`
      }
      if (!is.null(self$`Identifier.Ids`)) {
        OtherObject[['Identifier.Ids']] <-
          self$`Identifier.Ids`
      }

      OtherObject
    },
    fromJSON = function(OtherJson) {
      OtherObject <- jsonlite::fromJSON(OtherJson)
      if (!is.null(OtherObject$`Identifier.Eissn`)) {
        self$`Identifier.Eissn` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Eissn`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(OtherObject$`Contributor.ResearcherID.ResearcherIDs`)) {
        self$`Contributor.ResearcherID.ResearcherIDs` <- ApiClient$new()$deserializeObj(OtherObject$`Contributor.ResearcherID.ResearcherIDs`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(OtherObject$`Contributor.ResearcherID.Names`)) {
        self$`Contributor.ResearcherID.Names` <- ApiClient$new()$deserializeObj(OtherObject$`Contributor.ResearcherID.Names`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(OtherObject$`Identifier.Doi`)) {
        self$`Identifier.Doi` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Doi`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(OtherObject$`Identifier.Issn`)) {
        self$`Identifier.Issn` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Issn`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(OtherObject$`Identifier.article_no`)) {
        self$`Identifier.article_no` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.article_no`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(OtherObject$`Identifier.Isbn`)) {
        self$`Identifier.Isbn` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Isbn`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(OtherObject$`ResearcherID.Disclaimer`)) {
        self$`ResearcherID.Disclaimer` <- ApiClient$new()$deserializeObj(OtherObject$`ResearcherID.Disclaimer`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(OtherObject$`Identifier.Xref_Doi`)) {
        self$`Identifier.Xref_Doi` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Xref_Doi`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(OtherObject$`Identifier.Ids`)) {
        self$`Identifier.Ids` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Ids`, "array[character]", loadNamespace("woslite_r_client"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`Identifier.Eissn`)) {
        sprintf(
        '"Identifier.Eissn":
           [%s]
        ',
        paste(unlist(lapply(self$`Identifier.Eissn`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Contributor.ResearcherID.ResearcherIDs`)) {
        sprintf(
        '"Contributor.ResearcherID.ResearcherIDs":
           [%s]
        ',
        paste(unlist(lapply(self$`Contributor.ResearcherID.ResearcherIDs`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Contributor.ResearcherID.Names`)) {
        sprintf(
        '"Contributor.ResearcherID.Names":
           [%s]
        ',
        paste(unlist(lapply(self$`Contributor.ResearcherID.Names`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Identifier.Doi`)) {
        sprintf(
        '"Identifier.Doi":
           [%s]
        ',
        paste(unlist(lapply(self$`Identifier.Doi`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Identifier.Issn`)) {
        sprintf(
        '"Identifier.Issn":
           [%s]
        ',
        paste(unlist(lapply(self$`Identifier.Issn`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Identifier.article_no`)) {
        sprintf(
        '"Identifier.article_no":
           [%s]
        ',
        paste(unlist(lapply(self$`Identifier.article_no`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Identifier.Isbn`)) {
        sprintf(
        '"Identifier.Isbn":
           [%s]
        ',
        paste(unlist(lapply(self$`Identifier.Isbn`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`ResearcherID.Disclaimer`)) {
        sprintf(
        '"ResearcherID.Disclaimer":
           [%s]
        ',
        paste(unlist(lapply(self$`ResearcherID.Disclaimer`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Identifier.Xref_Doi`)) {
        sprintf(
        '"Identifier.Xref_Doi":
           [%s]
        ',
        paste(unlist(lapply(self$`Identifier.Xref_Doi`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Identifier.Ids`)) {
        sprintf(
        '"Identifier.Ids":
           [%s]
        ',
        paste(unlist(lapply(self$`Identifier.Ids`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(OtherJson) {
      OtherObject <- jsonlite::fromJSON(OtherJson)
      self$`Identifier.Eissn` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Eissn`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Contributor.ResearcherID.ResearcherIDs` <- ApiClient$new()$deserializeObj(OtherObject$`Contributor.ResearcherID.ResearcherIDs`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Contributor.ResearcherID.Names` <- ApiClient$new()$deserializeObj(OtherObject$`Contributor.ResearcherID.Names`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Identifier.Doi` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Doi`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Identifier.Issn` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Issn`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Identifier.article_no` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.article_no`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Identifier.Isbn` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Isbn`, "array[character]", loadNamespace("woslite_r_client"))
      self$`ResearcherID.Disclaimer` <- ApiClient$new()$deserializeObj(OtherObject$`ResearcherID.Disclaimer`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Identifier.Xref_Doi` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Xref_Doi`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Identifier.Ids` <- ApiClient$new()$deserializeObj(OtherObject$`Identifier.Ids`, "array[character]", loadNamespace("woslite_r_client"))
      self
    }
  )
)

