# Web of Science API Lite
#
# A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Source
#'
#' @description Source Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field Pages  list( character ) [optional]
#'
#' @field SourceTitle  list( character ) [optional]
#'
#' @field Issue  list( character ) [optional]
#'
#' @field Volume  list( character ) [optional]
#'
#' @field SpecialIssue  list( character ) [optional]
#'
#' @field BookSeriesTitle  list( character ) [optional]
#'
#' @field Published.BiblioDate  list( character ) [optional]
#'
#' @field Published.BiblioYear  list( character ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Source <- R6::R6Class(
  'Source',
  public = list(
    `Pages` = NULL,
    `SourceTitle` = NULL,
    `Issue` = NULL,
    `Volume` = NULL,
    `SpecialIssue` = NULL,
    `BookSeriesTitle` = NULL,
    `Published.BiblioDate` = NULL,
    `Published.BiblioYear` = NULL,
    initialize = function(
        `Pages`=NULL, `SourceTitle`=NULL, `Issue`=NULL, `Volume`=NULL, `SpecialIssue`=NULL, `BookSeriesTitle`=NULL, `Published.BiblioDate`=NULL, `Published.BiblioYear`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`Pages`)) {
        stopifnot(is.vector(`Pages`), length(`Pages`) != 0)
        sapply(`Pages`, function(x) stopifnot(is.character(x)))
        self$`Pages` <- `Pages`
      }
      if (!is.null(`SourceTitle`)) {
        stopifnot(is.vector(`SourceTitle`), length(`SourceTitle`) != 0)
        sapply(`SourceTitle`, function(x) stopifnot(is.character(x)))
        self$`SourceTitle` <- `SourceTitle`
      }
      if (!is.null(`Issue`)) {
        stopifnot(is.vector(`Issue`), length(`Issue`) != 0)
        sapply(`Issue`, function(x) stopifnot(is.character(x)))
        self$`Issue` <- `Issue`
      }
      if (!is.null(`Volume`)) {
        stopifnot(is.vector(`Volume`), length(`Volume`) != 0)
        sapply(`Volume`, function(x) stopifnot(is.character(x)))
        self$`Volume` <- `Volume`
      }
      if (!is.null(`SpecialIssue`)) {
        stopifnot(is.vector(`SpecialIssue`), length(`SpecialIssue`) != 0)
        sapply(`SpecialIssue`, function(x) stopifnot(is.character(x)))
        self$`SpecialIssue` <- `SpecialIssue`
      }
      if (!is.null(`BookSeriesTitle`)) {
        stopifnot(is.vector(`BookSeriesTitle`), length(`BookSeriesTitle`) != 0)
        sapply(`BookSeriesTitle`, function(x) stopifnot(is.character(x)))
        self$`BookSeriesTitle` <- `BookSeriesTitle`
      }
      if (!is.null(`Published.BiblioDate`)) {
        stopifnot(is.vector(`Published.BiblioDate`), length(`Published.BiblioDate`) != 0)
        sapply(`Published.BiblioDate`, function(x) stopifnot(is.character(x)))
        self$`Published.BiblioDate` <- `Published.BiblioDate`
      }
      if (!is.null(`Published.BiblioYear`)) {
        stopifnot(is.vector(`Published.BiblioYear`), length(`Published.BiblioYear`) != 0)
        sapply(`Published.BiblioYear`, function(x) stopifnot(is.character(x)))
        self$`Published.BiblioYear` <- `Published.BiblioYear`
      }
    },
    toJSON = function() {
      SourceObject <- list()
      if (!is.null(self$`Pages`)) {
        SourceObject[['Pages']] <-
          self$`Pages`
      }
      if (!is.null(self$`SourceTitle`)) {
        SourceObject[['SourceTitle']] <-
          self$`SourceTitle`
      }
      if (!is.null(self$`Issue`)) {
        SourceObject[['Issue']] <-
          self$`Issue`
      }
      if (!is.null(self$`Volume`)) {
        SourceObject[['Volume']] <-
          self$`Volume`
      }
      if (!is.null(self$`SpecialIssue`)) {
        SourceObject[['SpecialIssue']] <-
          self$`SpecialIssue`
      }
      if (!is.null(self$`BookSeriesTitle`)) {
        SourceObject[['BookSeriesTitle']] <-
          self$`BookSeriesTitle`
      }
      if (!is.null(self$`Published.BiblioDate`)) {
        SourceObject[['Published.BiblioDate']] <-
          self$`Published.BiblioDate`
      }
      if (!is.null(self$`Published.BiblioYear`)) {
        SourceObject[['Published.BiblioYear']] <-
          self$`Published.BiblioYear`
      }

      SourceObject
    },
    fromJSON = function(SourceJson) {
      SourceObject <- jsonlite::fromJSON(SourceJson)
      if (!is.null(SourceObject$`Pages`)) {
        self$`Pages` <- ApiClient$new()$deserializeObj(SourceObject$`Pages`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(SourceObject$`SourceTitle`)) {
        self$`SourceTitle` <- ApiClient$new()$deserializeObj(SourceObject$`SourceTitle`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(SourceObject$`Issue`)) {
        self$`Issue` <- ApiClient$new()$deserializeObj(SourceObject$`Issue`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(SourceObject$`Volume`)) {
        self$`Volume` <- ApiClient$new()$deserializeObj(SourceObject$`Volume`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(SourceObject$`SpecialIssue`)) {
        self$`SpecialIssue` <- ApiClient$new()$deserializeObj(SourceObject$`SpecialIssue`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(SourceObject$`BookSeriesTitle`)) {
        self$`BookSeriesTitle` <- ApiClient$new()$deserializeObj(SourceObject$`BookSeriesTitle`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(SourceObject$`Published.BiblioDate`)) {
        self$`Published.BiblioDate` <- ApiClient$new()$deserializeObj(SourceObject$`Published.BiblioDate`, "array[character]", loadNamespace("woslite_r_client"))
      }
      if (!is.null(SourceObject$`Published.BiblioYear`)) {
        self$`Published.BiblioYear` <- ApiClient$new()$deserializeObj(SourceObject$`Published.BiblioYear`, "array[character]", loadNamespace("woslite_r_client"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`Pages`)) {
        sprintf(
        '"Pages":
           [%s]
        ',
        paste(unlist(lapply(self$`Pages`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`SourceTitle`)) {
        sprintf(
        '"SourceTitle":
           [%s]
        ',
        paste(unlist(lapply(self$`SourceTitle`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Issue`)) {
        sprintf(
        '"Issue":
           [%s]
        ',
        paste(unlist(lapply(self$`Issue`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Volume`)) {
        sprintf(
        '"Volume":
           [%s]
        ',
        paste(unlist(lapply(self$`Volume`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`SpecialIssue`)) {
        sprintf(
        '"SpecialIssue":
           [%s]
        ',
        paste(unlist(lapply(self$`SpecialIssue`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`BookSeriesTitle`)) {
        sprintf(
        '"BookSeriesTitle":
           [%s]
        ',
        paste(unlist(lapply(self$`BookSeriesTitle`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Published.BiblioDate`)) {
        sprintf(
        '"Published.BiblioDate":
           [%s]
        ',
        paste(unlist(lapply(self$`Published.BiblioDate`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`Published.BiblioYear`)) {
        sprintf(
        '"Published.BiblioYear":
           [%s]
        ',
        paste(unlist(lapply(self$`Published.BiblioYear`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(SourceJson) {
      SourceObject <- jsonlite::fromJSON(SourceJson)
      self$`Pages` <- ApiClient$new()$deserializeObj(SourceObject$`Pages`, "array[character]", loadNamespace("woslite_r_client"))
      self$`SourceTitle` <- ApiClient$new()$deserializeObj(SourceObject$`SourceTitle`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Issue` <- ApiClient$new()$deserializeObj(SourceObject$`Issue`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Volume` <- ApiClient$new()$deserializeObj(SourceObject$`Volume`, "array[character]", loadNamespace("woslite_r_client"))
      self$`SpecialIssue` <- ApiClient$new()$deserializeObj(SourceObject$`SpecialIssue`, "array[character]", loadNamespace("woslite_r_client"))
      self$`BookSeriesTitle` <- ApiClient$new()$deserializeObj(SourceObject$`BookSeriesTitle`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Published.BiblioDate` <- ApiClient$new()$deserializeObj(SourceObject$`Published.BiblioDate`, "array[character]", loadNamespace("woslite_r_client"))
      self$`Published.BiblioYear` <- ApiClient$new()$deserializeObj(SourceObject$`Published.BiblioYear`, "array[character]", loadNamespace("woslite_r_client"))
      self
    }
  )
)

