# Web of Science API Lite
#
# A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WosLiteRecord
#'
#' @description WosLiteRecord Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field UT  character [optional]
#'
#' @field Title  \link{WosLiteRecordTitle} [optional]
#'
#' @field Doctype  \link{Doctype} [optional]
#'
#' @field Source  \link{Source} [optional]
#'
#' @field Author  \link{Author} [optional]
#'
#' @field Keyword  \link{Keyword} [optional]
#'
#' @field Other  \link{Other} [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WosLiteRecord <- R6::R6Class(
  'WosLiteRecord',
  public = list(
    `UT` = NULL,
    `Title` = NULL,
    `Doctype` = NULL,
    `Source` = NULL,
    `Author` = NULL,
    `Keyword` = NULL,
    `Other` = NULL,
    initialize = function(
        `UT`=NULL, `Title`=NULL, `Doctype`=NULL, `Source`=NULL, `Author`=NULL, `Keyword`=NULL, `Other`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`UT`)) {
        stopifnot(is.character(`UT`), length(`UT`) == 1)
        self$`UT` <- `UT`
      }
      if (!is.null(`Title`)) {
        stopifnot(R6::is.R6(`Title`))
        self$`Title` <- `Title`
      }
      if (!is.null(`Doctype`)) {
        stopifnot(R6::is.R6(`Doctype`))
        self$`Doctype` <- `Doctype`
      }
      if (!is.null(`Source`)) {
        stopifnot(R6::is.R6(`Source`))
        self$`Source` <- `Source`
      }
      if (!is.null(`Author`)) {
        stopifnot(R6::is.R6(`Author`))
        self$`Author` <- `Author`
      }
      if (!is.null(`Keyword`)) {
        stopifnot(R6::is.R6(`Keyword`))
        self$`Keyword` <- `Keyword`
      }
      if (!is.null(`Other`)) {
        stopifnot(R6::is.R6(`Other`))
        self$`Other` <- `Other`
      }
    },
    toJSON = function() {
      WosLiteRecordObject <- list()
      if (!is.null(self$`UT`)) {
        WosLiteRecordObject[['UT']] <-
          self$`UT`
      }
      if (!is.null(self$`Title`)) {
        WosLiteRecordObject[['Title']] <-
          self$`Title`$toJSON()
      }
      if (!is.null(self$`Doctype`)) {
        WosLiteRecordObject[['Doctype']] <-
          self$`Doctype`$toJSON()
      }
      if (!is.null(self$`Source`)) {
        WosLiteRecordObject[['Source']] <-
          self$`Source`$toJSON()
      }
      if (!is.null(self$`Author`)) {
        WosLiteRecordObject[['Author']] <-
          self$`Author`$toJSON()
      }
      if (!is.null(self$`Keyword`)) {
        WosLiteRecordObject[['Keyword']] <-
          self$`Keyword`$toJSON()
      }
      if (!is.null(self$`Other`)) {
        WosLiteRecordObject[['Other']] <-
          self$`Other`$toJSON()
      }

      WosLiteRecordObject
    },
    fromJSON = function(WosLiteRecordJson) {
      WosLiteRecordObject <- jsonlite::fromJSON(WosLiteRecordJson)
      if (!is.null(WosLiteRecordObject$`UT`)) {
        self$`UT` <- WosLiteRecordObject$`UT`
      }
      if (!is.null(WosLiteRecordObject$`Title`)) {
        TitleObject <- WosLiteRecordTitle$new()
        TitleObject$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Title, auto_unbox = TRUE, digits = NA))
        self$`Title` <- TitleObject
      }
      if (!is.null(WosLiteRecordObject$`Doctype`)) {
        DoctypeObject <- Doctype$new()
        DoctypeObject$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Doctype, auto_unbox = TRUE, digits = NA))
        self$`Doctype` <- DoctypeObject
      }
      if (!is.null(WosLiteRecordObject$`Source`)) {
        SourceObject <- Source$new()
        SourceObject$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Source, auto_unbox = TRUE, digits = NA))
        self$`Source` <- SourceObject
      }
      if (!is.null(WosLiteRecordObject$`Author`)) {
        AuthorObject <- Author$new()
        AuthorObject$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Author, auto_unbox = TRUE, digits = NA))
        self$`Author` <- AuthorObject
      }
      if (!is.null(WosLiteRecordObject$`Keyword`)) {
        KeywordObject <- Keyword$new()
        KeywordObject$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Keyword, auto_unbox = TRUE, digits = NA))
        self$`Keyword` <- KeywordObject
      }
      if (!is.null(WosLiteRecordObject$`Other`)) {
        OtherObject <- Other$new()
        OtherObject$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Other, auto_unbox = TRUE, digits = NA))
        self$`Other` <- OtherObject
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`UT`)) {
        sprintf(
        '"UT":
          "%s"
                ',
        self$`UT`
        )},
        if (!is.null(self$`Title`)) {
        sprintf(
        '"Title":
        %s
        ',
        jsonlite::toJSON(self$`Title`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`Doctype`)) {
        sprintf(
        '"Doctype":
        %s
        ',
        jsonlite::toJSON(self$`Doctype`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`Source`)) {
        sprintf(
        '"Source":
        %s
        ',
        jsonlite::toJSON(self$`Source`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`Author`)) {
        sprintf(
        '"Author":
        %s
        ',
        jsonlite::toJSON(self$`Author`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`Keyword`)) {
        sprintf(
        '"Keyword":
        %s
        ',
        jsonlite::toJSON(self$`Keyword`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`Other`)) {
        sprintf(
        '"Other":
        %s
        ',
        jsonlite::toJSON(self$`Other`$toJSON(), auto_unbox=TRUE, digits = NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WosLiteRecordJson) {
      WosLiteRecordObject <- jsonlite::fromJSON(WosLiteRecordJson)
      self$`UT` <- WosLiteRecordObject$`UT`
      self$`Title` <- WosLiteRecordTitle$new()$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Title, auto_unbox = TRUE, digits = NA))
      self$`Doctype` <- Doctype$new()$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Doctype, auto_unbox = TRUE, digits = NA))
      self$`Source` <- Source$new()$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Source, auto_unbox = TRUE, digits = NA))
      self$`Author` <- Author$new()$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Author, auto_unbox = TRUE, digits = NA))
      self$`Keyword` <- Keyword$new()$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Keyword, auto_unbox = TRUE, digits = NA))
      self$`Other` <- Other$new()$fromJSON(jsonlite::toJSON(WosLiteRecordObject$Other, auto_unbox = TRUE, digits = NA))
      self
    }
  )
)

