# Web of Science API Lite
#
# A responsive API that supports rich searching across the Web of Science Core Collection to retrieve core article metadata.  This service provides a great way to reuse Web of Science data both internally and externally to enhance  institutional repositories and research networking systems with best-in-class data. This API supports searching across the Web of Science to retrieve item-level metadata with limited fields:  - UT (Unique Identifier) - Authors - Author keywords - Document type - Title - Issue - Pages - Publication date - Source title - Volume - DOI - ISBN - ISSN   The API supports JSON and XML responses, and this documentation supports trying both response types. 
#
# The version of the OpenAPI document: 1.0
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title WosLiteResponse
#'
#' @description WosLiteResponse Class
#'
#' @format An \code{R6Class} generator object
#'
#' @field QueryResult  \link{QueryResult} [optional]
#'
#' @field Data  list( \link{WosLiteRecord} ) [optional]
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
WosLiteResponse <- R6::R6Class(
  'WosLiteResponse',
  public = list(
    `QueryResult` = NULL,
    `Data` = NULL,
    initialize = function(
        `QueryResult`=NULL, `Data`=NULL, ...
    ) {
      local.optional.var <- list(...)
      if (!is.null(`QueryResult`)) {
        stopifnot(R6::is.R6(`QueryResult`))
        self$`QueryResult` <- `QueryResult`
      }
      if (!is.null(`Data`)) {
        stopifnot(is.vector(`Data`), length(`Data`) != 0)
        sapply(`Data`, function(x) stopifnot(R6::is.R6(x)))
        self$`Data` <- `Data`
      }
    },
    toJSON = function() {
      WosLiteResponseObject <- list()
      if (!is.null(self$`QueryResult`)) {
        WosLiteResponseObject[['QueryResult']] <-
          self$`QueryResult`$toJSON()
      }
      if (!is.null(self$`Data`)) {
        WosLiteResponseObject[['Data']] <-
          lapply(self$`Data`, function(x) x$toJSON())
      }

      WosLiteResponseObject
    },
    fromJSON = function(WosLiteResponseJson) {
      WosLiteResponseObject <- jsonlite::fromJSON(WosLiteResponseJson)
      if (!is.null(WosLiteResponseObject$`QueryResult`)) {
        QueryResultObject <- QueryResult$new()
        QueryResultObject$fromJSON(jsonlite::toJSON(WosLiteResponseObject$QueryResult, auto_unbox = TRUE, digits = NA))
        self$`QueryResult` <- QueryResultObject
      }
      if (!is.null(WosLiteResponseObject$`Data`)) {
        self$`Data` <- ApiClient$new()$deserializeObj(WosLiteResponseObject$`Data`, "array[WosLiteRecord]", loadNamespace("woslite_r_client"))
      }
      self
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`QueryResult`)) {
        sprintf(
        '"QueryResult":
        %s
        ',
        jsonlite::toJSON(self$`QueryResult`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`Data`)) {
        sprintf(
        '"Data":
        [%s]
',
        paste(sapply(self$`Data`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(WosLiteResponseJson) {
      WosLiteResponseObject <- jsonlite::fromJSON(WosLiteResponseJson)
      self$`QueryResult` <- QueryResult$new()$fromJSON(jsonlite::toJSON(WosLiteResponseObject$QueryResult, auto_unbox = TRUE, digits = NA))
      self$`Data` <- ApiClient$new()$deserializeObj(WosLiteResponseObject$`Data`, "array[WosLiteRecord]", loadNamespace("woslite_r_client"))
      self
    }
  )
)

